### PR TITLE
refactor-save-product

### PR DESCRIPTION
**Pull request by HugoDaniel2000MELI**
Product Id auto incremente 
Duplicate Exceptions
Decrease product stock incomplete

### CODE REVIEW

**Comment by estpimentel** [comment]
[[BUG] POST new product](https://trello.com/c/o7Q9r1lR/18-bug-post-new-product)

**Comment by estpimentel** [comment]
[[BUG] POST new product](https://trello.com/c/o7Q9r1lR/18-bug-post-new-product)

**Comment by estpimentel** [comment]
[[BUG] POST new product](https://trello.com/c/o7Q9r1lR/18-bug-post-new-product)

**Comment by estpimentel** [comment]
[[Product] - productID auto e Exceptions para adição de novos produtos iguais](https://trello.com/c/wzSDQGvY/17-product-productid-auto-e-exceptions-para-adi%C3%A7%C3%A3o-de-novos-produtos)

**Comment by estpimentel** [comment]
[[Product] - productID auto e Exceptions para adição de novos produtos iguais](https://trello.com/c/wzSDQGvY/17-product-productid-auto-e-exceptions-para-adi%C3%A7%C3%A3o-de-novos-produtos)

**Comment by estpimentel** [comment]
[[Exception] R08 Service Unavailable](https://trello.com/c/GEGsiL2Y/19-exception-r08-service-unavailable)

**Review by rosymarianasantos — APPROVED** [review]

**Review by Atharr — APPROVED** [review]

**Review by brunacamposxx — APPROVED** [review]

**Pull request merged**
